spring.application.name=employee-management-gateway
server.port=8081

spring.cloud.gateway.server.webmvc.routes[0].id=employee-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8080
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/employees/**

employee.service.url=http://localhost:8080
employee.service.path=/api/v1/employees/**
employee.service.route-id=employee-service
gateway.rate-limit.capacity=10
gateway.rate-limit.period-seconds=60
